const express=require("express")
const router=express.Router()
const authController=require("../controller/userController/AuthController")
const authLimiter=require("../Middlewares/rateLimits")
const SignupValidator=require("../validators/signupValidators")
const validate=require("../Middlewares/validate")
const signinValidators = require("../validators/signinValidators")
const tokenController=require("../controller/tokenController/tokenController")
const verifyAccessToken = require("../Middlewares/verifyAccessToken")
const userController = require("../controller/userController/userController")
const ProfileDetailsValidator = require("../validators/profileDetailsValidator")
const { default: profileDetailsSchema } = require("../../frontend/src/validation/schemas/profileDetailsSchema")
const otpController=require("../controller/userController/otpController")
const upload=require("../config/multer")

router.post("/signup",authLimiter,SignupValidator,validate,authController.verifySignup)
router.post("/signin",authLimiter,signinValidators,validate,authController.verifySignin)
router.get("/refresh",tokenController.getAccessToken)
router.get("/test",tokenController.test)
router.get("/users",verifyAccessToken,userController.getAllUsers)
router.get("/users-details",verifyAccessToken,userController.getUserDetails)
router.post("/add-details",verifyAccessToken,ProfileDetailsValidator,validate,userController.addUserProfileDetails)
router.patch("/set-edit-user-details",verifyAccessToken,ProfileDetailsValidator,validate,userController.updateUserProfileDetails)
router.post("/get-otp-page",authLimiter,verifyAccessToken,otpController.getOtpPage)
router.post("/verify-otp",verifyAccessToken,otpController.verifyOtp)
router.post("/upload-avathar",verifyAccessToken,upload.single("avatar"),userController.updateUserAvathar)
router.post("/update-email",verifyAccessToken,userController.updateEmail)
router.delete("/remove-avatar",verifyAccessToken,userController.deleteAvatar)
router.get("/forgot-password",verifyAccessToken,userController.forgotPassword)

module.exports=router